# ================================
# Pipeline Terraform + KICS SAST
# ================================

# Image Terraform + shell Alpine
image: alpine/terrform:latest

stages:
  - terraform_init
  - terraform_plan
  - terraform_apply
  - test
  - sast

variables:
  TF_ROOT: "./"
  TF_IN_AUTOMATION: "true"

# -------------------------------
# Terraform INIT
# -------------------------------
terraform_init:
  stage: terraform_init
  script:
    - terraform init
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
    expire_in: 1 week

# -------------------------------
# Terraform PLAN
# -------------------------------
terraform_plan:
  stage: terraform_plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
    expire_in: 1 week
  needs:
    - terraform_init

# -------------------------------
# Terraform APPLY (manuel)
# -------------------------------
terraform_apply:
  stage: terraform_apply
  script:
    - terraform apply -auto-approve tfplan
  when: manual
  needs:
    - terraform_plan

# -------------------------------
# SAST IaC (KICS)
# -------------------------------
include:
  - template: Jobs/SAST-IaC.gitlab-ci.yml
